name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.CENTRAL_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.CENTRAL_GPG_SECRET_KEY_PASSWORD }} deploy -Pdeploy
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
